# Build settings

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title:output_ext
plugins:             [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title: "Mandar Upadhye"
description: "Powered by Jekyll and GitHub Pages"
author: "Mandar Upadhye"

# paginate: 2
# paginate_path: "/blog/page:num/"

collections:
  notes :
    output: true
    permalink: /:collection/:name
